// 08/05/2025 20:19:50
var lst_places = [
[,,,"."],
[,,,"Agua doce sc"],
[,,,"Aurea Rio Grande do Sul"],
[,,,"aurea, Rio Grande do Sul, Brasile"],
[,,,"Aurea, urea, Rio Grande do Sul, Brasile"],
[,,,"Baulandia, Renascenca, Parana, Brasile"],
[,,,"Bento Goncalves, Rio Grande do Sul, Brasile"],
[,,,"cacador"],
[,,,"Capinzal, Santa Catarina, Brasile"],
[,,,"CARAZINHO RS"],
[,,,"Casca, Rio Grande do Sul, Brasile"],
[,,,"Cascavel, Parana, Brasile"],
[,,,"cascavel"],
[,,,"Catanduvas SC"],
[,,,"Caxias do Sul, Rio Grande do Sul, Brasile"],
[,,,"Cemiterio da agua Verde - Curitiba, Parana"],
[,,,"Cemiterio de Rio Negro"],
[,,,"Cemiterio do Itacorubi Florianopolis"],
[,,,"Cemiterio PIO XII - Av XV Novembro"],
[,,,"cemiterio Santa Terezinha Guarapuava"],
[,,,"Chapeco, Santa Catarina, Brasile"],
[,,,"Constantina, Constantina, Rio Grande do Sul, Brasile"],
[,,,"Constantina, Rio Grande do Sul, Brasile"],
[,,,"Cuiaba, Cuiaba, Mato Grosso, Brasile"],
[,,,"Curitiba"],
[,,,"Dois Vizinhos, Parana, Brasile"],
[,,,"Edelira, Itapua, Paraguai"],
[,,,"Eneas Marques Pr"],
[,,,"Erechim-RS"],
[,,,"erechim"],
[,,,"Estado de Mato Grosso"],
[,,,"Feliz, Rio Grande do Sul, Brasile"],
[,,,"Floriano Peixoto, Rio Grande do Sul, Brasile"],
[,,,"Formosa do Sul"],
[,,,"Getulio Vargas, Rio Grande do Sul, Brasile"],
[,,,"Guapore, Rio Grande do Sul, Brasile"],
[,,,"Guapore"],
[,,,"Ibiraiaras, Rio Grande do Sul, Brasile"],
[,,,"Joacaba SC"],
[,,,"Lages SC"],
[,,,"Lagoa Vermelha - RS"],
[,,,"LAGOA VERMELHA"],
[,,,"LINHA SAO JOSE NONOAI-RS BRASILE"],
[,,,"Nao-Me-Toque, Rio Grande do Sul, Brasile"],
[,,,"Nonoai, Rio Grande do Sul, Brasile"],
[,,,"Nonoai-RS Brasil"],
[,,,"Nova Prata do Iguacu, Parana"],
[,,,"Nova prata rio grande do sul"],
[,,,"Nova Prata Rs Brasil"],
[,,,"Nova Prata, Rio Grande do Sul, Brasile"],
[,,,"Nova Prata"],
[,,,"Paim Filho"],
[,,,"Passo Fundo - RS"],
[,,,"Passo Fundo Rs"],
[,,,"Passo Fundo, Rio Grande do Sul, Brasile"],
[,,,"Passo Fundo"],
[,,,"Pato Branco, Parana, Brasile"],
[,,,"PIRATUBA"],
[,,,"Porto Alegre, Porto Alegre, Rio Grande do Sul, Brasile"],
[,,,"Porto Alegre, Rio Grande do Sul, Brasile"],
[,,,"Protasio Alves, Rio Grande do Sul, Brasile"],
[,,,"Protasio Alves"],
[,,,"Rio de Janeiro"],
[,,,"Rio Grande do Sul, Brasile"],
[,,,"Rio Grande do Sul"],
[,,,"Rio Negro - PR"],
[,,,"Sananduva, Rio Grande do Sul, Brasile"],
[,,,"Santa Maria, Rio Grande do Sul, Brasile"],
[,,,"Sao Domingos do Sul, Rio Grande do Sul, Brasile"],
[,,,"Sao Domingos do Sul, Sao Domingos do Sul, Rio Grande do Sul, Brasile"],
[,,,"sao Jorge rs"],
[,,,"Sao Jose do Cerrito, Santa Catarina, Brasile"],
[,,,"Sao Valentim, Rio Grande do Sul, Brasile"],
[,,,"Templo Curitiba"],
[,,,"Umin - Feltre"],
[,,,"Veranopolis, Rio Grande do Sul, Brasile"],
[,,,"Veranopolis-RS"],
[,,,"Vere, Parana, Brasile"],
[,,,"Vitorino, Parana, Brasile"],
["Argentina","Buenos Aires City","Buenos Aires",],
["Austria",,,],
["Brazil",,,],
["Brazil",,,"agua Doce, Santa Catarina"],
["Brazil",,,"agua Santa, agua Santa, Rio Grande do Sul"],
["Brazil",,,"aguas de Chapeco, Santa Catarina"],
["Brazil",,,"Alfredo Chaves, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Alfredo Chaves, Rio Grande do Sul"],
["Brazil",,,"Alto da Serra, Chapeco, Santa Catarina"],
["Brazil",,,"Alto Vere, Vere, Parana"],
["Brazil",,,"Amambai, Mato Grosso do Sul"],
["Brazil",,,"Ampere, Parana"],
["Brazil",,,"Andrû© da Rocha, Rio Grande do Sul"],
["Brazil",,,"Anita Garibaldi, Santa Catarina"],
["Brazil",,,"Anta Gorda, Rio Grande do Sul"],
["Brazil",,,"Antonio Prado, Antonio Prado, Rio Grande do Sul"],
["Brazil",,,"Antonio Prado, Rio Grande do Sul"],
["Brazil",,,"Antonio Prado,Rio Grande do Sul"],
["Brazil",,,"Araca, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Araca, Prata, Rio Grande do Sul"],
["Brazil",,,"Araruna, Araruna, Parana"],
["Brazil",,,"Aratiba, Aratiba, Rio Grande do Sul"],
["Brazil",,,"Ariquemes, Rondonia"],
["Brazil",,,"Arroio do Meio, Rio Grande do Sul"],
["Brazil",,,"Aruja, Sao Paulo"],
["Brazil",,,"Aurea, urea, Rio Grande do Sul"],
["Brazil",,,"Balisa, Gaurama, Rio Grande do Sul"],
["Brazil",,,"Baliza, Gaurama, Rio Grande do Sul"],
["Brazil",,,"Balneario Camboriu, Santa Catarina"],
["Brazil",,,"Balneario de Camboriu, Santa Catarina"],
["Brazil",,,"Barra do Pinheiro, Ipira, Santa Catarina"],
["Brazil",,,"Barra Velha, Santa Catarina"],
["Brazil",,,"Barracao, Rio Grande do Sul"],
["Brazil",,,"Barretos, Sao Paulo"],
["Brazil",,,"Barro, Erechim, Rio Grande do Sul"],
["Brazil",,,"Bauru, Sao Paulo"],
["Brazil",,,"Bela Vista, Sao Paulo"],
["Brazil",,,"Belem, Para"],
["Brazil",,,"Bento Goncalves, Bento Goncalves, Rio Grande do Sul"],
["Brazil",,,"Bento Goncalves, Rio Grande do Sul"],
["Brazil",,,"Bento Goncalves, RS"],
["Brazil",,,"Bituruna, Parana"],
["Brazil",,,"Blumenau, Santa Catarina"],
["Brazil",,,"Boa Esperanca do Iguacu, Parana"],
["Brazil",,,"Bocaiuva, Parana"],
["Brazil",,,"Bom Jesus, Bom Jesus, Rio Grande do Sul"],
["Brazil",,,"Bom Jesus, Rio Grande do Sul"],
["Brazil",,,"Braganey, Parana"],
["Brazil",,,"Cacador, Cacador, Santa Catarina"],
["Brazil",,,"Cacador, Santa Catarina"],
["Brazil",,,"Caceres, Mato Grosso"],
["Brazil",,,"Cacique doble, Cacique doble, Rio Grande do Sul"],
["Brazil",,,"Cacique doble, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Cacique doble, Rio Grande do Sul"],
["Brazil",,,"Caibi, Santa Catarina"],
["Brazil",,,"Camargo, Rio Grande do Sul"],
["Brazil",,,"Camboriu, Santa Catarina"],
["Brazil",,,"Campinas do Sul, Campinas do Sul, Rio Grande do Sul"],
["Brazil",,,"Campinas do Sul, Rio Grande do Sul"],
["Brazil",,,"Campinas, Sao Paulo"],
["Brazil",,,"Campo do Tenente, Parana"],
["Brazil",,,"Campo Grande, Mato Grosso do Sul"],
["Brazil",,,"Campos do Jordao, Sao Paulo"],
["Brazil",,,"Campos Novos, Santa Catarina"],
["Brazil",,,"Canela, Rio Grande do Sul"],
["Brazil",,,"Canoas, Rio Grande Do Sul"],
["Brazil",,,"Cantagalo, Parana"],
["Brazil",,,"Capanema, Parana"],
["Brazil",,,"Capao da Canoa, Rio Grande do Sul"],
["Brazil",,,"Capinzal, Santa Catarina, Cemiterio da comunidade de Rio Lindemberg"],
["Brazil",,,"Capinzal, Santa Catarina, Cemiterio da localidade de Lindemberg"],
["Brazil",,,"Capinzal, Santa Catarina"],
["Brazil",,,"Carazinho, Rio Grande do Sul"],
["Brazil",,,"Casca, Casca, Rio Grande do Sul"],
["Brazil",,,"Casca, Rio Grande do Sul"],
["Brazil",,,"Cascavel, Cascavel, Parana"],
["Brazil",,,"Cascavel, Parana"],
["Brazil",,,"Caseiros, Rio Grande do Sul"],
["Brazil",,,"Catanduvas, Catanduvas, Santa Catarina"],
["Brazil",,,"Catanduvas, Santa Catarina"],
["Brazil",,,"Caxambu, Caxambu do Sul, Santa Catarina"],
["Brazil",,,"Caxias do Sul, Caxias do Sul, Rio Grande do Sul"],
["Brazil",,,"Caxias do Sul, Rio Grande do Sul"],
["Brazil",,,"Celso Ramos, Santa Catarina"],
["Brazil",,,"Cemiterio Cristo Rei, Toledo, Parana"],
["Brazil",,,"Cemiterio da Capela, Jupia, Santa Catarina"],
["Brazil",,,"Cemiterio de Sede Independencia, Passo Fundo, Rio Grande do Sul"],
["Brazil",,,"Cemiterio Ecumenico de Chapeco, Santa Catarina, ."],
["Brazil",,,"Cemiterio Municipal de Nova Laranjeiras, Nova Laranjeiras, Parana"],
["Brazil",,,"Cemiterio Municipal Itacurubi - Sao Francisco de Assis, Florianopolis, Santa Catarina"],
["Brazil",,,"Cemiterio Municipal, Campo do Tenente, Parana"],
["Brazil",,,"Cemiterio Parque Das Araucarias Colombo, Colombo, Parana"],
["Brazil",,,"Cemiterio Parque Iguacu, Curitiba, Parana"],
["Brazil",,,"Cemiterio, Jaciara, Mato Grosso"],
["Brazil",,,"Cemiterio, Marau, Rio Grande do Sul"],
["Brazil",,,"Centenario, Rio Grande do Sul"],
["Brazil",,,"Cerejeiras, Rondonia"],
["Brazil",,,"Cerro Negro, Santa Catarina"],
["Brazil",,,"Chapeco, Chapeco, Santa Catarina"],
["Brazil",,,"Chapeco, Santa Catarina"],
["Brazil",,,"Chapeu, Jaquirana, Sao Francisco de Paula, Rio Grande do Sul"],
["Brazil",,,"Chimarrao, Andre da Rocha, Rio Grande do Sul, Cemiterio da Capela Santa Catarina"],
["Brazil",,,"Chopinzinho, Parana"],
["Brazil",,,"Cidade Gaucha, Parana"],
["Brazil",,,"Clemente Argolo, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"COLONIA GUARANY, RIO GRANDE DO SUL"],
["Brazil",,,"Colonia Sao Luiz de Franca, Vacaria, Rio Grande do Sul"],
["Brazil",,,"Colorado, Rio Grande do Sul"],
["Brazil",,,"Concordia, Santa Catarina"],
["Brazil",,,"Concordia,Santa Catarina"],
["Brazil",,,"Constantina, Rio Grande do Sul"],
["Brazil",,,"Corbelia, Parana"],
["Brazil",,,"Coronel Ferreira, Soledade, Rio Grande do Sul"],
["Brazil",,,"Coronel Freitas, Santa Catarina"],
["Brazil",,,"Coronel Martins, Santa Catarina"],
["Brazil",,,"Coronel Vivida, Parana"],
["Brazil",,,"Cotipora, Rio Grande do Sul"],
["Brazil",,,"Coxilha, Passo Fundo, Rio Grande do Sul"],
["Brazil",,,"Coxilha,RS"],
["Brazil",,,"Criuva, Caxias do Sul, Rio Grande do Sul"],
["Brazil",,,"Cruz Alta, Rio Grande do Sul"],
["Brazil",,,"Cruzeiro do Iguacu, Dois Vizinhos, Parana"],
["Brazil",,,"Cruzeiro do Iguacu, Parana"],
["Brazil",,,"Cuiaba, Mato Grosso"],
["Brazil",,,"Curitiba, Parana"],
["Brazil",,,"Curitiba,Parana"],
["Brazil",,,"Curitibanos, Santa Catarina"],
["Brazil",,,"Descanso, Santa Catarina"],
["Brazil",,,"Dois Vizinhos, Dois Vizinhos, Parana"],
["Brazil",,,"Dois Vizinhos, Parana"],
["Brazil",,,"Dourados, Mato Grosso do Sul"],
["Brazil",,,"Encantado, Rio Grande do Sul"],
["Brazil",,,"Eneas Marques, Eneas Marques, Parana"],
["Brazil",,,"Eneas Marques, Parana"],
["Brazil",,,"Erebango, Rio Grande do Sul"],
["Brazil",,,"Erechim, Erechim, Rio Grande do Sul"],
["Brazil",,,"Erechim, Rio Grande do Sul"],
["Brazil",,,"Erexim, Rio Grande do Sul, ."],
["Brazil",,,"Erval Grande, Rio Grande do Sul"],
["Brazil",,,"Esmeralda, Rio Grande do Sul"],
["Brazil",,,"Estacao, Rio Grande do Sul"],
["Brazil",,,"Estancia Velha, Rio Grande do Sul"],
["Brazil",,,"Fagundes Varela, Fagundes Varela, Rio Grande do Sul"],
["Brazil",,,"Fagundes Varela, Rio Grande do Sul"],
["Brazil",,,"Farroupilha, Rio Grande do Sul"],
["Brazil",,,"Faxinal dos Guedes, Santa Catarina"],
["Brazil",,,"Flores da Cunha , Rio Grande do Sul"],
["Brazil",,,"Flores da Cunha, Flores da Cunha, Rio Grande do Sul"],
["Brazil",,,"Flores da Cunha, Prata, Rio Grande do Sul"],
["Brazil",,,"Flores da Cunha, Rio Grande do Sul"],
["Brazil",,,"Floriano Peixoto, Rio Grande do Sul"],
["Brazil",,,"Florianopolis, Santa Catarina"],
["Brazil",,,"Formosa do Sul, Santa Catarina"],
["Brazil",,,"Foz do Iguacu, Parana"],
["Brazil",,,"Fraiburgo, Fraiburgo, Santa Catarina"],
["Brazil",,,"Fraiburgo, Santa Catarina"],
["Brazil",,,"Francisco Beltrao, Francisco Beltrao, Parana"],
["Brazil",,,"Francisco Beltrao, Parana"],
["Brazil",,,"Galopolis,Rs"],
["Brazil",,,"Galvao, Santa Catarina"],
["Brazil",,,"Garibaldi, Rio Grande do Sul"],
["Brazil",,,"Gaspar, Santa Catarina"],
["Brazil",,,"Gaurama, Erechim, Rio Grande do Sul"],
["Brazil",,,"Gaurama, Gaurama, Erechim, Rio Grande do Sul"],
["Brazil",,,"Gaurama, Gaurama, Rio Grande do Sul"],
["Brazil",,,"Gaurama, Rio Grande do Sul"],
["Brazil",,,"General Camara, Rio Grande do Sul"],
["Brazil",,,"Gentil, Gentil, Rio Grande do Sul"],
["Brazil",,,"Gentil, Rio Grande do Sul"],
["Brazil",,,"Getulio Vargas, Erechim, Rio Grande do Sul"],
["Brazil",,,"Getulio Vargas, Getulio Vargas, Rio Grande do Sul"],
["Brazil",,,"Getulio Vargas, Rio Grande do Sul"],
["Brazil",,,"Getulio Vargas, Soledade, Rio Grande do Sul"],
["Brazil",,,"Goiania, Goias"],
["Brazil",,,"Grao Para, Santa Catarina"],
["Brazil",,,"Gravatai, Rio Grande do Sul"],
["Brazil",,,"Guabiju, Rio Grande do Sul, Cemiterio Municipal"],
["Brazil",,,"Guabiju, Rio Grande do Sul"],
["Brazil",,,"Guaira, Parana"],
["Brazil",,,"Guapore, Guapore, Rio Grande do Sul"],
["Brazil",,,"Guapore, Rio Grande do Sul"],
["Brazil",,,"Guaraniacu, Parana"],
["Brazil",,,"Guaranta do Norte, Mato Grosso"],
["Brazil",,,"Guarapuava, Parana"],
["Brazil",,,"Guararapes, Antonio Prado, Rio Grande do Sul"],
["Brazil",,,"Gustavo Berthier, Sao Jose do Ouro, Rio Grande do Sul"],
["Brazil",,,"Gustavo Berthier, Tupanci, Sao Jose do Ouro, Rio Grande do Sul"],
["Brazil",,,"Herval d'Oeste, Santa Catarina"],
["Brazil",,,"Hospital Marcelino Champagnat, Curitiba, Parana"],
["Brazil",,,"Hospital Salvatoriano Divino Salvador, Videira, Santa Catarina"],
["Brazil",,,"Ibiaca, Rio Grande do Sul"],
["Brazil",,,"Ibiam, Santa Catarina"],
["Brazil",,,"Ibiraiaras, Ibiraiaras, Rio Grande do Sul"],
["Brazil",,,"Ibiraiaras, Rio Grande do Sul"],
["Brazil",,,"Ibiraiaras, RS"],
["Brazil",,,"Igreja Nossa Senhora da Conceicao, Passo Fundo, Rio Grande do Sul"],
["Brazil",,,"Instituto Virmond, Guarapuava, Parana"],
["Brazil",,,"Ipe, Rio Grande do Sul"],
["Brazil",,,"Ipe, Vacaria, Rio Grande do Sul"],
["Brazil",,,"Ipira, Santa Catarina"],
["Brazil",,,"Ipuacu, Ipuacu, Santa Catarina"],
["Brazil",,,"Ipuacu, Santa Catarina"],
["Brazil",,,"Irani, Santa Catarina"],
["Brazil",,,"Ita, Santa Catarina"],
["Brazil",,,"Itai, RS"],
["Brazil",,,"Itajai, Itajai, Santa Catarina"],
["Brazil",,,"Itajai, Santa Catarina"],
["Brazil",,,"Itajuba, Descanso, Santa Catarina"],
["Brazil",,,"Itapecerica da Serra, Sao Paulo"],
["Brazil",,,"Itapejara Oeste, Parana"],
["Brazil",,,"Itapoa, Santa Catarina"],
["Brazil",,,"Itapuca, Rio Grande do Sul"],
["Brazil",,,"Ivaipora, Parana"],
["Brazil",,,"Jaciara, Mato Grosso"],
["Brazil",,,"Jacutinga, Rio Grande do Sul"],
["Brazil",,,"Jaguari, Rio Grande do Sul"],
["Brazil",,,"Jaguari,Rio Grande do Sul"],
["Brazil",,,"Joacaba, Santa Catarina"],
["Brazil",,,"Joao Pessoa, Joao Pessoa, Paraiba"],
["Brazil",,,"Joao Pessoa, Paraiba"],
["Brazil",,,"Joinville, Santa Catarina"],
["Brazil",,,"Lages, Santa Catarina"],
["Brazil",,,"Lagoa Vermelha, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Lajeado dos Pintos, Concordia, Santa Catarina"],
["Brazil",,,"Lajeado Grande, Santa Catarina"],
["Brazil",,,"Lapa, Parana"],
["Brazil",,,"Laranjeiras do Sul, Parana"],
["Brazil",,,"Liberato Salzano, Rio Grande do Sul"],
["Brazil",,,"Lindoia do Sul, Santa Catarina"],
["Brazil",,,"Linha 13, Araca, Prata, Rio Grande do Sul"],
["Brazil",,,"Linha Carlos Gomes, Marema, Santa Catarina, ."],
["Brazil",,,"Linha Pinheiro Alto, Ouro, Santa Catarina"],
["Brazil",,,"Loreto 2Âº Legua, Caxias do Sul, Rio Grande do Sul"],
["Brazil",,,"Machadinho, Machadinho, Rio Grande do Sul"],
["Brazil",,,"Machadinho, Rio Grande do Sul"],
["Brazil",,,"Mafra, Santa Catarina"],
["Brazil",,,"Manaus, Amazonas"],
["Brazil",,,"Mandirituba, Parana"],
["Brazil",,,"Mangueirinha, Parana"],
["Brazil",,,"Marata, Sao Domingos, Santa Catarina"],
["Brazil",,,"Marau, Marau, Rio Grande do Sul"],
["Brazil",,,"Marau, Rio Grande do Sul"],
["Brazil",,,"Marcelino Ramos, Rio Grande do Sul"],
["Brazil",,,"Mariana Pimentel, Porto Alegre, Rio Grande do Sul"],
["Brazil",,,"Maringa, Parana"],
["Brazil",,,"Mariopolis, Parana"],
["Brazil",,,"Marmeleiro, Parana"],
["Brazil",,,"Matelandia, Parana"],
["Brazil",,,"Mato Grosso, Mato Grosso"],
["Brazil",,,"Matupa, Matupa, Mato Grosso"],
["Brazil",,,"Maximiliano de Almaeida, Rio Grande do Sul"],
["Brazil",,,"Maximiliano de Almeida, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Maximiliano de Almeida, Maximiliano de Almaeida, Rio Grande do Sul"],
["Brazil",,,"Maximiliano de Almeida, Rio Grande do Sul"],
["Brazil",,,"Medianeira, Parana"],
["Brazil",,,"Missal, Parana"],
["Brazil",,,"Montauri, Guapore, Rio Grande do Sul"],
["Brazil",,,"Monte Alto, Sao Paulo"],
["Brazil",,,"Montenegro, Rio Grande do Sul"],
["Brazil",,,"Muitos Capoes, Vacaria, Rio Grande do Sul"],
["Brazil",,,"Nobres, Mato Grosso"],
["Brazil",,,"Nonoai, Rio Grande do Sul"],
["Brazil",,,"Nossa Senhora do Rosario, Concordia, Santa Catarina"],
["Brazil",,,"Nova Araca, Nova Prata, Rio Grande do Sul"],
["Brazil",,,"Nova Araca, Rio Grande do Sul"],
["Brazil",,,"Nova Bassano, Rio Grande do Sul"],
["Brazil",,,"Nova Erechim, Santa Catarina"],
["Brazil",,,"nova ibiaca,Serra Alta, Santa Catarina"],
["Brazil",,,"Nova Laranjeiras, Nova Laranjeiras, Parana"],
["Brazil",,,"Nova Laranjeiras, Parana"],
["Brazil",,,"Nova Londrina, Parana"],
["Brazil",,,"Nova Padua, Caxias, Sao Sebastiao do Cai, Rio Grande do Sul"],
["Brazil",,,"Nova Padua, Rio Grande do Sul"],
["Brazil",,,"Nova Prata do Iguacu, Nova Prata do Iguacu, Parana"],
["Brazil",,,"Nova Prata do Iguacu, Parana"],
["Brazil",,,"Nova Prata, Nova Petropolis, Rio Grande do Sul"],
["Brazil",,,"Nova Prata, Rio Grande do Sul, Cemiterio da Capela Nossa Senhora da Saude"],
["Brazil",,,"Nova Prata, Rio Grande do Sul, Cemiterio Municipal"],
["Brazil",,,"Nova Prata, Rio Grande do Sul"],
["Brazil",,,"Nova Prata, Rs"],
["Brazil",,,"Nova Prata,Rio Grande Do Sul"],
["Brazil",,,"Nova Prata,Rs"],
["Brazil",,,"Nova Roma do Sul, Nova Roma do Sul, Rio Grande do Sul"],
["Brazil",,,"Nova Roma do Sul, Rio Grande do Sul"],
["Brazil",,,"Nova Roma, Antonio Prado, Rio Grande do Sul"],
["Brazil",,,"Nova Roma, Nova Roma do Sul, Rio Grande do Sul"],
["Brazil",,,"Nova Trento, Rio Grande do Sul"],
["Brazil",,,"Novo Progresso, Para"],
["Brazil",,,"Of,Nova Prata,Rio Grande Do Sul"],
["Brazil",,,"Orleaes, Santa Catarina"],
["Brazil",,,"Ouro, Cruzeiro, Santa Catarina"],
["Brazil",,,"Ouro, Ouro, Santa Catarina"],
["Brazil",,,"Ouro, Santa Catarina, Cemiterio da localidade de Lindemberg"],
["Brazil",,,"Ouro, Santa Catarina"],
["Brazil",,,"Paim Filho, Paim Filho, Rio Grande do Sul"],
["Brazil",,,"Paim Filho, Rio Grande do Sul"],
["Brazil",,,"Pain Filho, Rio Grande do Sul"],
["Brazil",,,"Palma Sola, Santa Catarina"],
["Brazil",,,"Palmas, Parana"],
["Brazil",,,"Palotina, Parana"],
["Brazil",,,"Parai, Parai, Rio Grande do Sul"],
["Brazil",,,"Parai, Rio Grande do Sul"],
["Brazil",,,"Parana"],
["Brazil",,,"Paranagua, Parana"],
["Brazil",,,"Passo Fundo, Rio Grande do Sul"],
["Brazil",,,"Passo Fundo, RS"],
["Brazil",,,"Passo Fundo, Santa Catarina"],
["Brazil",,,"Passo Fundo,Rio Grande do Sul"],
["Brazil",,,"Passo Fundo,RS"],
["Brazil",,,"Passos Maia, Santa Catarina"],
["Brazil",,,"Pato Branco, Parana"],
["Brazil",,,"Peritiba, Santa Catarina"],
["Brazil",,,"Perola d'Oeste, Parana"],
["Brazil",,,"Picarras, Santa Catarina"],
["Brazil",,,"Pinhalzinho, Eneas Marques, Parana"],
["Brazil",,,"Pinhalzinho, Pinhalzinho, Santa Catarina"],
["Brazil",,,"Pinhalzinho, Santa Catarina"],
["Brazil",,,"Pinto Bandeira, Rio Grande do Sul"],
["Brazil",,,"Piratuba, Santa Catarina"],
["Brazil",,,"Planalto, Rio Grande do Sul"],
["Brazil",,,"Pontal do Parana, Parana"],
["Brazil",,,"Ponte Serrada, Santa Catarina"],
["Brazil",,,"Porto Alegre, Porto Alegre, Rio Grande do Sul"],
["Brazil",,,"Porto Alegre, Rio Grande do Sul"],
["Brazil",,,"Porto dos Gauchos, Mato Grosso"],
["Brazil",,,"Porto Uniao, Santa Catarina"],
["Brazil",,,"Potasio Alves, RS"],
["Brazil",,,"Pouso Alegre, Minas Gerais"],
["Brazil",,,"Prata, 3Âº distr de Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Prata, Rio Grande do Sul"],
["Brazil",,,"Primavera do Leste, Mato Grosso"],
["Brazil",,,"Protasio Alves, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Protasio Alves, Nova Prata, Rio Grande do Sul"],
["Brazil",,,"Protasio Alves, Prata, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Protasio Alves, Prata, Rio Grande do Sul"],
["Brazil",,,"Protasio Alves, Protasio Alves, Rio Grande do Sul"],
["Brazil",,,"Protasio Alves, Rio Grande do Sul, Cemiterio Municipal"],
["Brazil",,,"Protasio Alves, Rio Grande do Sul"],
["Brazil",,,"Protasio Alves,Rio Grande do Sul"],
["Brazil",,,"Quatro Irmaos, Rio Grande do Sul"],
["Brazil",,,"Quedas do Iguacu, Parana"],
["Brazil",,,"Quilombo, Santa Catarina"],
["Brazil",,,"Realeza, Parana"],
["Brazil",,,"Recife, Pernambuco"],
["Brazil",,,"Renascenca, Parana"],
["Brazil",,,"Rio Cacador, Campos Novos, Santa Catarina"],
["Brazil",,,"Rio das Antas, Santa Catarina"],
["Brazil",,,"Rio de Janeiro, Rio de Janeiro"],
["Brazil",,,"Rio Grande do Sul"],
["Brazil",,,"Rio Negro, Parana"],
["Brazil",,,"Rio Novo, Erechim, Rio Grande do Sul"],
["Brazil",,,"Rio Telha, Ibiaca, Rio Grande do Sul"],
["Brazil",,,"Ronda Alta, Rio Grande do Sul"],
["Brazil",,,"Rondonopolis, Mato Grosso"],
["Brazil",,,"Sagrado Coracao de Jesus, Antonio Prado, Rio Grande do Sul"],
["Brazil",,,"Salgado Filho, Parana"],
["Brazil",,,"Salto do Lontra, Parana"],
["Brazil",,,"Sananduva, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Sananduva, Rio Grande do Sul"],
["Brazil",,,"Sananduva, Sananduva, Rio Grande do Sul"],
["Brazil",,,"Santa Catarina"],
["Brazil",,,"Santa Clara, Joacaba, Santa Catarina"],
["Brazil",,,"Santa Cruz do Timbo, Porto Uniao, Santa Catarina"],
["Brazil",,,"Santa Helena, Parana"],
["Brazil",,,"Santa Izabel do Oeste, Parana"],
["Brazil",,,"Santa Lucia do Piai, Rio Grande Do Sul"],
["Brazil",,,"Santa Maria, Rio Grande do Sul"],
["Brazil",,,"Santana do Araguaia, Para"],
["Brazil",,,"Santiago do Sul, Santa Catarina"],
["Brazil",,,"Sao Braz, Porto Alegre, Rio Grande do Sul"],
["Brazil",,,"Sao Caetano, Sao Jorge, Rio Grande do Sul"],
["Brazil",,,"Sao Domingos do Sul, Rio Grande do Sul"],
["Brazil",,,"Sao Domingos, Santa Catarina"],
["Brazil",,,"Sao Francisco de Paula, Rio Grande do Sul"],
["Brazil",,,"Sao Francisco de Paula, Sao Francisco de Paula, Rio Grande do Sul"],
["Brazil",,,"Sao Joao Batista, Sananduva, Rio Grande do Sul"],
["Brazil",,,"Sao Joao da Urtiga, Paim Filho, Rio Grande do Sul"],
["Brazil",,,"Sao Joao da Urtiga, Rio Grande do Sul"],
["Brazil",,,"Sao Joao da Urtiga, Sao Joao da Urtiga, Rio Grande do Sul"],
["Brazil",,,"Sao Joao do Itaperiu, Santa Catarina"],
["Brazil",,,"Sao Joao Giaretta, Paulo Bento, Rio Grande do Sul"],
["Brazil",,,"Sao Joao, Parana"],
["Brazil",,,"Sao Joaquim, Santa Catarina"],
["Brazil",,,"Sao Jorge, Rio Grande do Sul"],
["Brazil",,,"Sao Jose do Carreiro, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Sao Jose do Cedro, Santa Catarina"],
["Brazil",,,"Sao Jose do Ouro, Rio Grande do Sul"],
["Brazil",,,"Sao Jose do Ouro, Sao Jose do Ouro, Rio Grande do Sul"],
["Brazil",,,"Sao Jose do Rio Claro, Mato Grosso"],
["Brazil",,,"Sao Jose dos Campos, Sao Paulo"],
["Brazil",,,"Sao Jose dos Pinhais, Parana"],
["Brazil",,,"Sao Jose dos Pinhais, Sao Jose dos Pinhais, Parana"],
["Brazil",,,"Sao Jose Ouro, Cacique Doble, Rio Grande do Sul"],
["Brazil",,,"Sao Jose, Santa Catarina"],
["Brazil",,,"Sao Leopoldo, Rio Grande do Sul"],
["Brazil",,,"Sao Lourenco do Oeste, Santa Catarina"],
["Brazil",,,"Sao Luiz de Cascara, Guapore, Rio Grande do Sul"],
["Brazil",,,"Sao Luiz de Franca, Rio Grande do Sul"],
["Brazil",,,"Sao Luiz, Vacaria, Rio Grande do Sul"],
["Brazil",,,"Sao Luizinho, Passo Fundo, Rio Grande do Sul"],
["Brazil",,,"Sao Miguel do Iguacu, Parana"],
["Brazil",,,"Sao Miguel do Oeste, Santa Catarina"],
["Brazil",,,"Sao Paulo Apostolo, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Sao Paulo da Cruz, Sananduva, Rio Grande do Sul"],
["Brazil",,,"Sao Paulo, Sao Paulo"],
["Brazil",,,"Sao Paulo"],
["Brazil",,,"Sao Pedro, Guabiju, Rio Grande do Sul"],
["Brazil",,,"Sao Sebastiao do Cai, Sao Sebastiao do Cai, Rio Grande do Sul"],
["Brazil",,,"Sao Valentim do Sul, Rio Grande do Sul"],
["Brazil",,,"Sao Valentim, Rio Grande do Sul"],
["Brazil",,,"Sarandi, Rio Grande do Sul"],
["Brazil",,,"Sarandi, RS"],
["Brazil",,,"Saudades, Santa Catarina"],
["Brazil",,,"Seara, Santa Catarina"],
["Brazil",,,"Segredo, Ipe, Rio Grande do Sul"],
["Brazil",,,"Segredo, Rio Grande do Sul"],
["Brazil",,,"Serafina Correa, Rio Grande do Sul"],
["Brazil",,,"Severiano de Almeida, Rio Grande do Sul"],
["Brazil",,,"Sidrolandia, Mato Grosso do Sul"],
["Brazil",,,"Sidrolandia, Sidrolandia, Mato Grosso do Sul"],
["Brazil",,,"Sinop, Mato Grosso"],
["Brazil",,,"Sinop, Sinop, Mato Grosso"],
["Brazil",,,"Sonora, Mato Grosso do Sul"],
["Brazil",,,"Tangara da Serra, Mato Grosso"],
["Brazil",,,"Tangara, Santa Catarina"],
["Brazil",,,"Tapejara, Passo Fundo, Rio Grande do Sul"],
["Brazil",,,"Tapejara, Rio Grande do Sul"],
["Brazil",,,"Taquara Verde, Cacador, Santa Catarina"],
["Brazil",,,"Teixeira, Passo Fundo, Rio Grande do Sul"],
["Brazil",,,"Templo de Curitiba, Curitiba, Parana"],
["Brazil",,,"Timbo, Santa Catarina"],
["Brazil",,,"Toledo, Parana"],
["Brazil",,,"Tres Barras do Parana, Parana"],
["Brazil",,,"Treze de Maio, Aurea, Erechim, Rio Grande do Sul"],
["Brazil",,,"Treze de Maio, Erechim, Rio Grande do Sul"],
["Brazil",,,"Trindade do Sul, Rio Grande do Sul"],
["Brazil",,,"Triunfo, Rio Grande do Sul"],
["Brazil",,,"Tupanci do Sul, Rio Grande do Sul"],
["Brazil",,,"Tupinamba, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Umuarama, Parana"],
["Brazil",,,"Uniao da Vitoria, Parana"],
["Brazil",,,"Urussanga, Santa Catarina"],
["Brazil",,,"Vacaria, Rio Grande do Sul"],
["Brazil",,,"Vacaria, RS"],
["Brazil",,,"Vanini, Rio Grande do Sul"],
["Brazil",,,"Vazulmiro Dutra, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Vazulmiro Dutra, Sao Jose do Ouro, Lagoa Vermelha, Rio Grande do Sul"],
["Brazil",,,"Veranopolis, Rio Grande do Sul"],
["Brazil",,,"Veranopolis, Veranopolis, Rio Grande do Sul"],
["Brazil",,,"Vere, Parana"],
["Brazil",,,"Viadutos, Rio Grande do Sul"],
["Brazil",,,"Videira, Santa Catarina"],
["Brazil",,,"Vila de Tupanci, Sao Jose do Ouro, Rio Grande do Sul"],
["Brazil",,,"Vila de Tupandi, Sao Jose do Ouro, Rio Grande do Sul"],
["Brazil",,,"Vila Segredo, Ipe, Rio Grande do Sul"],
["Brazil",,,"Vila Segredo, Vacaria, Rio Grande do Sul"],
["Brazil",,,"Vila Souza, Sao Jose do Ouro, Rio Grande do Sul"],
["Brazil",,,"Vista Alegre do Prata, Rio Grande do Sul"],
["Brazil",,,"Vista Alegre, Prata, Rio Grande do Sul"],
["Brazil",,,"Vista Alegre, Rio Grande do Sul"],
["Brazil",,,"Xanxere, Santa Catarina"],
["Brazil",,,"Xaxim, Santa Catarina"],
["Dominican Republic",,,"Cacique, Distrito Nacional"],
["Italia",,,],
["Italia",,,"Beluno"],
["Italia","?","Rovigo","Bergantino"],
["Italia","Abruzzi","Aquila","Santa Maria del Ponte"],
["Italia","Lombardia","Bergamo",],
["Italia","Lombardia","Bergamo","Romano di Lombardia"],
["Italia","Lombardia","Bergamo","Romano"],
["Italia","Lombardia",,"Gonzaga, Mantova"],
["Italia","Lombardia",,"Mantova"],
["Italia","Lombardia",,"Sailetto, Suzzara, Mantova"],
["Italia","Lombardia",,"San Benedetto Po, Mantova"],
["Italia","Lombardia",,"Sustinente, Mantova"],
["Italia","Molise","Campobasso",],
["Italia","Sicile","Caltanisetta","Gela"],
["Italia","Venetia","Belluno",],
["Italia","Venetia","Belluno","Cesiomaggiore"],
["Italia","Venetia","Belluno","Feltre"],
["Italia","Venetia","Belluno","San Giorgio Martire, Feltre"],
["Italia","Venetia","Belluno","San Gregorio nelle Alpi"],
["Italia","Venetia","Belluno","San Gregorio, San Gregorio"],
["Italia","Venetia","Belluno","San Gregorio"],
["Italia","Venetia","Belluno","Toschian, Cesiomaggiore"],
["Italia","Venetia","Belluno","Umin, Feltre"],
["Italia","Venetia","Belluno","Vellai, Feltre"],
["Italia","Venetia","Belluno","Villabruna, Feltre"],
["Italia","Venetia","Belluno","Villabruna, Umin, Feltre"],
["Italia","Venetia","Bolzano","Crosara, Vicenza"],
["Italia","Venetia","Modolo","Belluno, Belluno"],
["Italia","Venetia","Padoue",],
["Italia","Venetia","Padoue","Abbazia Pisani, Villa del Conte"],
["Italia","Venetia","Padoue","Battaglia Terme"],
["Italia","Venetia","Padoue","Battaglia"],
["Italia","Venetia","Padoue","Galzignano Terme"],
["Italia","Venetia","Padoue","Galzignano"],
["Italia","Venetia","Padoue","San Pietro Montagnon"],
["Italia","Venetia","Padoue","Santa Croce Bigolina, Cittadella"],
["Italia","Venetia","Padoue","Teolo"],
["Italia","Venetia","Padoue","Venezia"],
["Italia","Venetia","Padoue","Villa del Conte"],
["Italia","Venetia","Padua","Abano Terme"],
["Italia","Venetia","San Bartolomeo","Gallio, Vicenza"],
["Italia","Venetia","Santa Giustina","Belluno"],
["Italia","Venetia","Sedico","Belluno"],
["Italia","Venetia","Sedico","Beluno"],
["Italia","Venetia","Sospirold","Belluno"],
["Italia","Venetia","Treviso",],
["Italia","Venetia","Treviso","Pederobba"],
["Italia","Venetia","Veneto","Bergantino, Rovigo"],
["Italia","Venetia","Veneto","Castelnovo Bariano, Rovigo"],
["Italia","Venetia","Vicenza",],
["Italia","Venetia","Vicenza","Altavilla"],
["Italia","Venetia","Vicenza","Bassano del Grappa"],
["Italia","Venetia","Vicenza","Cismon del Grappa"],
["Italia","Venetia","Vicenza","Crosara, Marostica"],
["Italia","Venetia","Vicenza","Laverda, Mure di Salcedo"],
["Italia","Venetia","Vicenza","Marostica"],
["Italia","Venetia","Vicenza","Mure di Salcedo"],
["Italia","Venetia","Vicenza","Roana"],
["Italia","Venetia","Vicenza","Rotzo"],
["Italia","Venetia","Vicenza","Vallonara, Marostica"],
["Peru",,,"Lima, Lima, Lima"],
["Poland",,,],
["United States of America","South Carolina",,"Ouro"],
["Venezuela",,,"Cua, Miranda"]];
